export const types = {
  // Auth
  SIGN_UP: 'SIGN_UP',
  LOGIN: 'LOGIN',
  SET_USER: 'SET_USER',
  SEND_LOGIN_MAIL: 'SEND_LOGIN_MAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  VERIFY_CODE: 'VERIFY_CODE',

  // App
  GET_APPLICATIONS: 'GET_APPLICATIONS',
  GET_API_KEYS: 'GET_API_KEYS',
  GET_WALLETS: 'GET_WALLETS',
  GET_HISTORIES: 'GET_HISTORIES',
};
