export const types = {
  // Auth
  SIGN_UP: 'SIGN_UP',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_USER: 'SET_USER',
  UPDATE_USER: 'UPDATE_USER',
  CLEAR_USER: 'CLEAR_USER',
  SEND_LOGIN_MAIL: 'SEND_LOGIN_MAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  VERIFY_CODE: 'VERIFY_CODE',
  CONFIRM_REGISTRATION: 'CONFIRM_REGISTRATION',
  FETCH_USER_INFO: 'FETCH_USER_INFO',
  // App
  GET_APPLICATIONS: 'GET_APPLICATIONS',
  GET_API_KEYS: 'GET_API_KEYS',
  GET_API_KEY: 'GET_API_KEY',
  GET_WALLETS: 'GET_WALLETS',
  GET_HISTORIES: 'GET_HISTORIES',
  GET_WHITE_LISTED_IPS: 'GET_WHITE_LISTED_IPS',
  GET_ADMINS: 'GET_ADMINS',
  RESET_USER_PASSWORD: 'RESET_USER_PASSWORD',
  DISABLE_API_KEY: 'DISABLE_API_KEY',
  ENABLE_API_KEY: 'ENABLE_API_KEY',

  APPROVE_USER: 'APPROVE_USER',
  DENY_USER: 'DENY_USER',
};
